### ISSUE TITLE
VfpException: SQL: TOP requires an ORDER BY.

### ISSUE THREAD

**Issue by spottedmahn** [tombrothers/LINQtoVFP#2]
![image](https://user-images.githubusercontent.com/14079228/54927610-de45b400-4ee8-11e9-932f-d14b8a50fb77.png)

Any thoughts on fix for this?

**Comment by tombrothers** [comment]
If you look at the SQL tab you can see the generated VFP SQL and if you were to run that SQL in the VFP IDE you would see the same error.  The reason that this error occurs is because the generated SQL is roughly “select top 1 * from appusers” but the VFP engine requires and “order by” clause if there is a “top” clause.  You can fix this by explicitly setting an OrderBy before the Take.

**Comment by spottedmahn** [comment]
Hi @tombrothers - I get that 👍, I'm saying, what can we do **in code** to automate this?

Is there a point in the code where it can check if there is a `Take()` w/o and `OrderBy()` then add `OrderBy()`?  If so, the next question would be can we inspect the 'model' and pick a field to order by? 🤔

**Comment by tombrothers** [comment]
It has been a long time since I’ve worked with this code (at least on the expressions side) so off the top of my head I couldn’t provide direction but it should be possible.  The codebase has the concept of expression rewriters that are used to manipulate the linq expressions before the sql is generated.  You could look at those to see if you could figure out how to write a missing order by rewriter.  I did something similar in the VfpEntityFrameworkProvider2.  You could look at [that code](https://github.com/tombrothers/VfpEntityFrameworkProvider2/blob/master/Source/VfpEntityFrameworkProvider/Visitors/Rewriters/MissingOrderByRewritter.cs) for guidance as to the logic that could be implemented.

**Comment by spottedmahn** [comment]
Thanks!  I'll take a look 😊
